### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by as280093** [Elastic1/piccoma-downloader#3]
```
error occurred. retry  TypeError: Cannot read properties of undefined (reading 'split')
    at PiccomaPage.saveEpisode (C:\Users\mac\piccoma-downloader-main\lib\piccoma.js:124:51)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (C:\Users\mac\piccoma-downloader-main\piccoma.js:58:11)

```

**Comment by Elastic1** [comment]
Sorry for the delay.
I'll deal with it later ASAP 😺
