### ISSUE TITLE
溺愛のシナリオがダウンロードできない

### ISSUE THREAD

**Issue by Yucie** [Elastic1/piccoma-downloader#5]
accessing 溺愛のシナリオ...第1話～第23話
error occurred. retry  Error: SOI not found
    at constructor.parse (C:\snapshot\piccoma-downloader\node_modules\pureimage\dist\pureimage-umd.cjs:12276:19)
    at Object.decode (C:\snapshot\piccoma-downloader\node_modules\pureimage\dist\pureimage-umd.cjs:12735:15)
    at IncomingMessage.<anonymous> (C:\snapshot\piccoma-downloader\node_modules\pureimage\dist\pureimage-umd.cjs:12887:47)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
error occurred. retry  Error: SOI not found
    at constructor.parse (C:\snapshot\piccoma-downloader\node_modules\pureimage\dist\pureimage-umd.cjs:12276:19)
    at Object.decode (C:\snapshot\piccoma-downloader\node_modules\pureimage\dist\pureimage-umd.cjs:12735:15)
    at IncomingMessage.<anonymous> (C:\snapshot\piccoma-downloader\node_modules\pureimage\dist\pureimage-umd.cjs:12887:47)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

原因が不明ですが、ダウンロードできなかった。
https://piccoma.com/web/product/80683

**Comment by Elastic1** [comment]
なかなか時間が取れなくて遅くなりました💦
最新バージョンで修正しました！
https://github.com/Elastic1/piccoma-downloader/releases
